include:
  - board: nice_nano_v2
    shield: my_kb_left
    west-config-path: config/west.yml
  - board: nice_nano_v2
    shield: my_kb_right
    west-config-path: config/west.yml
  - board: nice_nano_v2
    shield: settings_reset
  